[package]
name = "hifumi-e2e"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
hifumi = { path = "../types" }
yuuka = "0.6"

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
